### ISSUE TITLE
Layout is a little messy, and it is a little difficult to understand specificity of each stats, 

### ISSUE THREAD

**Issue by adityagi02** [mycontroller-org/backend#1]
For a proper view, we have to change it to Dark Mode and make every stats on dashboard a little more specific by using  ,or making tables and increasing sizes of some stat boxes.

**Comment by jkandasa** [comment]
@adityagi02 Can you add a screenshot? It will be easier to understand

**Comment by jkandasa** [comment]
I do not see enough information to work on this issue.
Please reopen with the detailed information. Thanks!
